{
 "title": "vuln-commander dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "query": "SELECT distinct(project_name) FROM vc_view_project_vulnerabilities_statistic\n"
   },
   {
    "name": "control_type",
    "query": "SELECT enumlabel\nFROM pg_enum\nJOIN pg_type ON pg_enum.enumtypid = pg_type.oid\nWHERE pg_type.typname = 'connectortype';"
   },
   {
    "name": "severity",
    "query": "SELECT enumlabel\nFROM pg_enum\nJOIN pg_type ON pg_enum.enumtypid = pg_type.oid\nWHERE pg_type.typname = 'vulnseverity';"
   },
   {
    "name": "team",
    "query": "SELECT enumlabel\nFROM pg_enum\nJOIN pg_type ON pg_enum.enumtypid = pg_type.oid\nWHERE pg_type.typname = 'userteam';"
   }
  ]
 },
 "panels": [
  {
   "title": "Main dashboard",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  project_status,\n  project_name,\n  project_url,\n  project_team,\n  project_default_branch,\n  last_commit_author,\n  last_commit_email,\n  last_commit_created,\n  info_vulns,\n  low_vulns,\n  medium_vulns,\n  high_vulns,\n  critical_vulns,\n  new,\n  closed,\n  false_positive,\n  reopened,\n  awaiting_review,\n  gss as \"GSS\",\n  iac as \"IAC\",\n  sca_license as \"SCA-license\",\n  sca_vuln as \"SCA-vulnerabilities\"\nFROM\n  vc_view_general_vulnerabilities_statistic\nWHERE \nproject_name = ANY(string_to_array('${project_name:csv}', ','))\n"
    }
   ]
  },
  {
   "title": "General statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of vulnerabilities by severity",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(info_vulns) as \"info\",\n  SUM(low_vulns) as \"low\",\n  SUM(medium_vulns) as \"medium\",\n  SUM(high_vulns) as \"high\",\n  SUM(critical_vulns) as \"critical\"\nFROM vc_view_general_vulnerabilities_statistic "
      }
     ]
    },
    {
     "title": "Number of vulnerabilities by status",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  COUNT(v.id) FILTER (WHERE v.status = 'new') as \"new\",\n  COUNT(v.id) FILTER (WHERE v.status = 'closed') as \"closed\",\n  COUNT(v.id) FILTER (WHERE v.status = 'awaiting_review') as \"awaiting_review\", \n  COUNT(v.id) FILTER (WHERE v.status = 'false_positive') as \"false_positive\", \n  COUNT(v.id) FILTER (WHERE v.status = 'reopened') as \"reopened\"  \nFROM vc_vuln v\n\n"
      }
     ]
    },
    {
     "title": "Number of vulnerabilities by scanner",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  COUNT(v.id) FILTER (WHERE v.connector_type = 'gss') as \"gss\",\n  COUNT(v.id) FILTER (WHERE v.connector_type = 'iac') as \"iac\",\n  COUNT(v.id) FILTER (WHERE v.connector_type = 'sca_vuln') as \"sca_vuln\", \n  COUNT(v.id) FILTER (WHERE v.connector_type = 'sca_license') as \"sca_license\"\nFROM vc_vuln v\n\n"
      }
     ]
    },
    {
     "title": "Number of vulnerabilities by scanner and severity level",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT\n  control_type,\n  severity,\n  COUNT(*)\nFROM vc_view_project_vulnerabilities_statistic\nGROUP BY control_type, severity\nORDER BY COUNT(*) DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Team statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Team vulnerabilities count",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  COUNT(v.id) FILTER (WHERE v.severity = 'info') as \"info\",\n  COUNT(v.id) FILTER (WHERE v.severity = 'low') as \"low\",\n  COUNT(v.id) FILTER (WHERE v.severity = 'medium') as \"medium\", \n  COUNT(v.id) FILTER (WHERE v.severity = 'high') as \"high\", \n  COUNT(v.id) FILTER (WHERE v.severity = 'critical') as \"critical\"  \nFROM vc_vuln v\nJOIN vc_project p on p.id = v.project_id\nWHERE p.team = ANY(string_to_array('${team:csv}', ',')::userteam[])\nAND v.status = 'new'\n"
      }
     ]
    }
   ]
  },
  {
   "title": "IAC statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of vulnerabilities by platform",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  platform,\n  COUNT(*)\nFROM vc_view_iac_vulnerabilities_statistic\nGROUP BY platform\nORDER BY COUNT(*) DESC"
      }
     ]
    },
    {
     "title": "Number of vulnerabilities by CWE",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  cwe_id,\n  COUNT(*) AS count\nFROM vc_view_iac_vulnerabilities_statistic\nGROUP BY cwe_id\nORDER BY count DESC;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "SCA statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 50 packages with vulnerabilities by frequency of use",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\n  package_name,\n  COUNT(*)\nFROM vc_view_sca_vuln_vulnerabilities_statistic\nGROUP BY package_name\nORDER BY COUNT(*) DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Vulnerability details by scanner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GSS vulnerabilities details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  project_name,\n  severity,\n  status,\n  filepath,\n  line,\n  code_snippet,\n  rule_name,\n  rule_text_id,\n  commit_id,\n  branch\nFROM\n  vc_view_gss_vulnerabilities_statistic\nWHERE project_name = ANY(string_to_array('${project_name:csv}', ','))\n  AND severity = ANY(string_to_array('${severity:csv}', ',')::vulnseverity[])\nORDER BY \n  CASE severity\n    WHEN 'critical' THEN 1\n    WHEN 'high'     THEN 2\n    WHEN 'medium'   THEN 3\n    WHEN 'low'      THEN 4\n    WHEN 'info'     THEN 5\n    ELSE 6\n  END ASC"
      }
     ]
    },
    {
     "title": "IAC vulnerabilities details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  project_name,\n  severity,\n  status,\n  filepath,\n  line,\n  platform,\n  category,\n  description,\n  actual_value,\n  recommended_value,\n  recommendation_url,\n  cwe_url,\n  rule_name,\n  rule_text_id,\n  rule_search_key\nFROM\n  vc_view_iac_vulnerabilities_statistic\nWHERE project_name = ANY(string_to_array('${project_name:csv}', ','))\n  AND severity = ANY(string_to_array('${severity:csv}', ',')::vulnseverity[])\nORDER BY \n  CASE severity\n    WHEN 'critical' THEN 1\n    WHEN 'high'     THEN 2\n    WHEN 'medium'   THEN 3\n    WHEN 'low'      THEN 4\n    WHEN 'info'     THEN 5\n    ELSE 6\n  END ASC"
      }
     ]
    },
    {
     "title": "SCA license details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\n  project_name,\n  severity,\n  status,\n  filepath,\n  package_name,\n  license,\n  license_description\nFROM\n  vc_view_sca_license_vulnerabilities_statistic\nWHERE project_name = ANY(string_to_array('${project_name:csv}', ','))\n  AND severity = ANY(string_to_array('${severity:csv}', ',')::vulnseverity[])\nORDER BY \n  CASE severity\n    WHEN 'critical' THEN 1\n    WHEN 'high'     THEN 2\n    WHEN 'medium'   THEN 3\n    WHEN 'info'     THEN 4\n    ELSE 5\n  END ASC"
      }
     ]
    },
    {
     "title": "SCA vulnerabilities details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\n  project_name,\n  severity,\n  status,\n  package_manager,\n  package_name,\n  package_fixed_version,\n  package_vuln_status,\n  vuln_title,\n  vuln_description,\n  cvss_score as \"vendor_cvss\",\n  package_installed_version,\n  recommendation_url\nFROM\n  vc_view_sca_vuln_vulnerabilities_statistic\nWHERE project_name = ANY(string_to_array('${project_name:csv}', ','))\n  AND severity = ANY(string_to_array('${severity:csv}', ',')::vulnseverity[])\nORDER BY \n  CASE severity\n    WHEN 'critical' THEN 1\n    WHEN 'high'     THEN 2\n    WHEN 'medium'   THEN 3\n    WHEN 'info'     THEN 4\n    ELSE 5\n  END ASC"
      }
     ]
    }
   ]
  }
 ]
}