[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vuln-commander-shared"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pydantic>=2.11.7"]

[tool.setuptools]
package-dir = { "shared" = "." }
packages = ["shared", "shared.schemas"]
